-- Generated by `wraith contract propose` from the checkout-contract recording,
-- then reviewed and promoted for the provider-CI demo.

local wraith = require('lib.wraith')
-- Compatibility marker for `sigil run` smoke-mode capability inference.
-- The branch is never executed; real traffic goes through wraith.* wrappers.
if false then sigil.get("/") end

local function expect_eq(actual, expected, label)
  if actual ~= expected then
    error(label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
  end
end

local function expect_present(value, label)
  if value == nil then
    error(label .. ": expected field to be present")
  end
end

return {
  title    = "checkout-web customer/order contract",
  priority = "P1",
  policy   = { capabilities = {"http", "wraith"} },
  meta     = {
    lifecycle_state = "active",
    inference_seed  = "sha256:e2d67cffb75d97f509995ba5f4c3287c09c64ae5d541ec2b7a9c496bd59ba455",
  },

  run = function()
    local health = wraith.get("/health")
    expect_eq(health.status, 200, "health status")
    expect_eq(health.json.ok, true, "health ok")

    local customer = wraith.post("/customers", {
      name = "CHECKOUT_QA",
      plan = "enterprise",
    })
    expect_eq(customer.status, 201, "create customer status")
    expect_present(customer.json.id, "customer id")
    expect_eq(
      customer.json.licenseAgreementID,
      "lic_" .. customer.json.id .. "_enterprise",
      "customer licenseAgreementID"
    )

    local customer_read = wraith.get("/customers/" .. customer.json.id)
    expect_eq(customer_read.status, 200, "read customer status")
    expect_eq(customer_read.json.id, customer.json.id, "read customer id")
    expect_eq(
      customer_read.json.licenseAgreementID,
      customer.json.licenseAgreementID,
      "read customer licenseAgreementID"
    )

    local order = wraith.post("/orders", {
      customerId = customer.json.id,
      items = {
        {
          quantity = 3,
          sku = "seat",
          unitCents = 1200,
        },
        {
          quantity = 1,
          sku = "support",
          unitCents = 5000,
        },
      },
    })
    expect_eq(order.status, 201, "create order status")
    expect_present(order.json.id, "order id")
    expect_eq(order.json.customerId, customer.json.id, "order customerId")
    expect_eq(order.json.totalCents, 8600, "order computed totalCents")
    expect_eq(
      order.json.licenseAgreementID,
      customer.json.licenseAgreementID,
      "order licenseAgreementID"
    )

    local order_read = wraith.get("/orders/" .. order.json.id)
    expect_eq(order_read.status, 200, "read order status")
    expect_eq(order_read.json.id, order.json.id, "read order id")
    expect_eq(
      order_read.json.licenseAgreementID,
      order.json.licenseAgreementID,
      "read order licenseAgreementID"
    )

    local summary = wraith.get("/orders/summary")
    expect_eq(summary.status, 200, "summary status")
    expect_eq(summary.json.currency, "USD", "summary currency")
    expect_eq(summary.json.orderCount, 1, "summary orderCount")
    expect_eq(summary.json.totalCents, 8600, "summary totalCents")
  end,
}
